#!/bin/bash

# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add "Holberton School" to the index file
sudo bash -c 'echo "Holberton School" > /var/www/html/index.html'

# Start Nginx without using systemctl
sudo service nginx start
