#!/usr/bin/env bash
# Script to configure Nginx for a 301 redirection

# Install Nginx if not installed
sudo apt update -y
sudo apt install -y nginx

# Create a backup of the default config
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Add redirection to Nginx config
sudo sed -i '/server_name _;/a \\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }\n' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
