#!/usr/bin/env bash
# Configure a custom 404 page

# Create the custom 404 page in remote server
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Update Nginx to use the custom 404 page
sed -i 's#error_page 404 /404.html;#error_page 404 /404.html;\n\tlocation = /404.html { root /var/www/html; }#' /etc/nginx/sites-available/default

# Reload Nginx
nginx -s reload
